### ISSUE TITLE
So how i build it? 

### ISSUE THREAD

**Issue by Dokman** [GollumTeam/GollumCoreLib#7]
I had to use eclipse or gradlew or how i can build the Library?

**Comment by Smeagolworms4** [comment]
Yes. It's a problem to configure the sub project GollumCoreLib.

If you can create a configuration that GollumCoreLib compiles before MorePiston and be linked to the project in eclipse, "you will save my life."

**Comment by Smeagolworms4** [comment]
The configuration for 1.6.4 and 1.7.10 is finish and works
